[project]
name = "kaggle-datasets"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.5",
    "pandas>=2.3.1",
    "pandas-stubs==2.3.0.250703",
    "scikit-learn>=1.7.1",
]
